- docs/changes.rst
- docs/midi_files.rst
- mido/__init__.py
- mido/messages.py
- mido/midifiles.py
- mido/test_midifiles2.py
Added the ability to use file objects as well as filenames when reading, writing and saving MIDI files. This allows you to create a MIDI file dynamically (possibly *not* using `mido`), save it to an `io.BytesIO`, and then play that in-memory file, without having to create an intermediate external file. Of course the file (and/or the MidiFile) can still be saved to an external file.
midifiles.py: changes to ByteReader, ByteWriter, MidiFile.save. Parameters and instance attribute `filename` renamed to `filename_or_file`.
test_midifiles2.py: unittests of new feature
messages.py: corrected docstrings, error messages
__init__.py: version number bump
Docs: midi_files.rst -- corrected an example; added a paragraph (which could be better-placed) on new feature
> Added the ability to read and write file objects as well as filenames

- mido/sockets.py
I couldn't get PortServer to run (missing field yield_ports) because it was using the wrong base class `__init__`.
> use the correct __init__ for PortServer

- mido/midifiles.py
It appears that you can only slice `MidiTrack` instances; indexing doesn't work:
```
In [1]: import mido
In [2]: t = mido.MidiTrack()
In [3]: t.append(mido.Message('note_on'))
In [4]: t[0]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-d0a24a012877> in <module>()
----> 1 t[0]
/usr/local/lib/python2.7/site-packages/mido-1.1.15-py2.7.egg/mido/midifiles.pyc in __getitem__(self, index_or_slice)
157         # Todo: this make a copy of the list. Is there a better way?
158         lst = list.__getitem__(self, index_or_slice)
--> 159         return self.__class__(lst)
160
161     def __repr__(self):
TypeError: 'Message' object is not iterable
In [5]: t[0:]
Out[5]: [<message …
```
> Don't construct MidiTrack when index is provided

- mido/backends/portmidi_init.py
Hi,
I noticed there was a discrepancy in the dll_name variable for Darwin platform which prevented mido to load the portmidi dynamic library properly on OS X and made all my mido-based examples crash.
> Fix dll name for darwin platform

- mido/backends/rtmidi.py
MidiIn/Out constructors need correct `rtapi` param otherwise they can
fail to find ports.
fixes #90
> Pass appropriate API param to rtmidi backend Input/Output classes

- mido/midifiles/midifiles.py
- mido/midifiles/test_midifiles.py
This prevents a problem I had while trying to read a (presumably corrupt) midi file that claimed to have a message with length 34359738240. Before this patch, python crashed after trying to allocate too much memory. After this patch, I can cleanly catch the IOError exception.
> Prevent trying to read extremely long messages

- mido/backends/portmidi.py
Hello,
There's an issue on the port selection code of the PortMidi backend which is solved by the first commit of this PR.
The second commit changes the logic for selecting ports of _get_name_device. Give that each device has two properties (is_input, is_output), I believe the presented is much saner way of doing said selection.
> Fix portmidi backend

- mido/backends/portmidi_init.py
This was fixed in commit d051be32e4f6ee52f4570bcfed445aae20a92526 but then broken again with codebase cleaning in df6d05a6abcf6139ca31715dd3ed5450b2d98e96
>  Re-added import ctypes.byref to fix portmidi backend

- mido/ports.py
I saw this while going over the source!
I haven't actually encountered a problem due to what I perceive is an issue on this line - it might be the correct behavior for some reason I haven't figured out.
If it's right, let me know and I'll change the commit to be a comment explaining it.
Thanks for an excellent library!
> Pass `block` parameter through in `MultiPort._receive()`

- README.rst
- docs/index.rst
- docs/roadmap.rst
Solves issue #175. 
Updated references to point to the updated repository name.
Affected files: `README.rst`, `docs/index.rst`, and `docs/roadmap.rst`.
> Changed instances of olemb/mido to mido/mido for GitHub links

- docs/midi_files.rst
- examples/midifiles/create_midi_file.py
- examples/midifiles/play_midi_file.py
- mido/midifiles/midifiles.py
Addresses #160
Also modify midifile examples to include fine-grained events
and report time drift.
> Improve MidiFile.play to avoid time drift.

- .flake8
- MANIFEST.in
- mido/midifiles/meta.py
- tox.ini
Also fixed a couple of line that flake8 complained about.
Tox runs again without any errors (at least locally). I've silenced a few errors. We may want to go back and look into them in the future.
> Fixed broken flake8 invocation by moving its options to a config file.

- bin/mido-ports
fixes typo in environment variable name MIDO_DEAFULT_INPUT to MIDO_DEFAULT_INPUT
> fix typo in environment variable name MIDO_DEAFULT_INPUT

- mido/frozen.py
- mido/messages/messages.py
- mido/midifiles/meta.py
- mido/midifiles/midifiles.py
- mido/midifiles/tracks.py
- tests/messages/test_messages.py
- tests/midifiles/test_meta.py
- tests/midifiles/test_midifiles.py
- tests/midifiles/test_tracks.py
- tests/test_frozen.py
Fixes #162.
Example:
```Python console
>>> from mido import Message, MidiTrack, MidiFile
>>> m = Message('note_on', channel=1, note=2, time=3)
>>> m
Message('note_on', note=2, velocity=64, channel=1, time=3)
>>> t = MidiTrack([Message('note_on', channel=1, note=2, time=3),
... Message('note_off', channel=1, note=2, time=3)])
>>> t
MidiTrack([
Message('note_on', note=2, velocity=64, channel=1, time=3),
Message('note_off', note=2, velocity=64, channel=1, time=3)])
>>> f = MidiFile(type=1, ticks_per_beat=123, tracks=[t])
>>> f
MidiFile(type=1, ticks_per_beat=123, tracks=[
MidiTrack([
Message('note_on', note=2, velocity=64, channel=1, time=3),
Message('note_off', note=2, velocity=64, channel=1, time=3)])
])
>>> f2 = eval(repr(f))
>>> f2
MidiFile(type=1, ticks_per_beat=123, tracks=[ …
```
> eval-able repr() for Message, MidiTrack, MidiFile

- docs/changes.rst
- docs/index.rst
- docs/intro.rst
- docs/messages.rst
- docs/meta_message_types.rst
- docs/midi_files.rst
- docs/parsing.rst
- docs/resources.rst
- docs/string_encoding.rst
- mido/midifiles/midifiles.py
- mido/midifiles/tracks.py
* Switched from % syntax to .format().
* Updated the docs to use the new repr() format.
* Fixed a mistake in a docs example. (Import from wrong module.)
* Updated the name of the MIDI Association.
* Removed the `__str__()` methods from MidiTrack and MidiFile.
The code in `MidiFile.__repr__()` and `MidiTrack().__repr__()` is a bit hard to follow but it's OK for now.
> Completed repr() changes

- mido/backends/rtmidi.py
Some remarks:
- https://github.com/mido/mido/blob/master/mido/backends/rtmidi.py#L119 and https://github.com/mido/mido/blob/master/mido/backends/rtmidi.py#L184
still use MidiIn and MidiOut
- examples might need to be fixed, I'm not sure
- other rtMidi-based backends might need some work too
> Fix RtMidi leaks when using MidiIn or MidiOut (#256)

- mido/ports.py
This is tiny but I kept seeing it as I read through the code and eventually... :-D
In `ports.multi_receive`, you _do_ want to make a copy of the incoming `ports` list, but only once, not each time through the loop!  So I moved it out of the loop.
> Only copy ports list once in ports.multi_receive

- README.rst
- docs/contributing.rst
- docs/roadmap.rst
Also removed block about looking for maintainers although we still welcome people who want to help with code review, issues, and planning.
> documentation now refers to "discussions"; closes #265

- mido/midifiles/tracks.py
It's now clear that there are three cases.
> Tiny refactor of MidiTrack.__repr__() for clarity.

- docs/messages.rst
While reading the docs I noticed a misspelling, opening a PR to fix it.
> Fixing misspelling of easiest

- .github/workflows/test.yml
- docs/contributing.rst
I need to also actually rename the branch itself.
> in testing and contribution docs, use "main" instead of "master"; closes #272

- mido/backends/rtmidi.py
- mido/backends/rtmidi_python.py
Devices with both input and output were listed twice. Before my changes:
```python
>>> import mido
>>> mido.get_input_names()
['Midi Through:Midi Through Port-0 14:0', 'Neutron(1):Neutron(1) MIDI 1 16:0', 'Keybow 2040:Keybow 2040 MIDI 1 20:0', 'Midi Through:Midi Through Port-0 14:0', 'Neutron(1):Neutron(1) MIDI 1 16:0', 'Keybow 2040:Keybow 2040 MIDI 1 20:0']
>>> import mido.backends.rtmidi
>>> mido.backends.rtmidi.get_devices()
[{'name': 'Midi Through:Midi Through Port-0 14:0', 'is_input': True, 'is_output': True}, {'name': 'Neutron(1):Neutron(1) MIDI 1 16:0', 'is_input': True, 'is_output': True}, {'name': 'Keybow 2040:Keybow 2040 MIDI 1 20:0', 'is_input': True, 'is_output': True}, {'name': 'Midi Through:Midi Through Port-0 14:0', 'is_input': True, 'is_output': True}, {'name': …
```
> Fix for duplicated devices in mido output

- mido/sockets.py
Fixes #290.  More info is available [here](https://github.com/kyleclaassen/mido/commit/f38bbd703b4114c2bd70ac7e4cad2d58d01c44e7#commitcomment-47639569).
> Fix PortServer disconnect crash in Python 3

- mido/backends/backend.py
> backends: Fix typos in docstrings

- docs/parsing.rst
Correct the intended commands and output which demo the `Parser().feed_byte()` and `Parser().feed()` use.
> docs: Fix example code for parsing

- mido/messages/messages.py
A few typos fixed in docstrings; no functionality changes.
> messages: Fix typos in docstrings

- .github/workflows/test.yml
- README.rst
- docs/backends/rtmidi_python.rst
- docs/contributing.rst
- docs/installing.rst
The pip executable could point to any installed version of Python.
Specifying the Python interpreter avoids installing to the wrong version.
Related to #263
> Specify Python version explicitly for running pip

- .github/workflows/test.yml
The current versions issues warnings of deprecation
> Update GitHub action runners

- docs/code-of-conduct.rst
- docs/index.rst
- missing: contact information and procedure for handling incidents (search for "warning" for text we need to adapt before merging)
- part of #270
> draft code of conduct

- .flake8
- mido/backends/portmidi.py
- mido/backends/portmidi_init.py
Follows up on #413.
Instead of using star imports, let's just be specific about what we're using from `ctypes` and that's that 😄
> Don't use star imports in portmidi_init

- mido/midifiles/midifiles.py
The MidiFile.iter() function calls merge_tracks() on its first iteration. I have examples of this function taking many tenths of seconds to execute. This causes issues when using Midifile.play() to provide the timing for midi playback, as the first note(s) will play long after their calculated 'input_time' (because they have to wait on merge_tracks()).
This change calls merge_tracks on MidiFile instantiation and after each add_track() call, removing the need to call it in MidiFile.iter()
> move complex function out of __iter__() first loop

- .github/workflows/documentation.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- docs/contributing.rst
- docs/glossary.rst
- pyproject.toml
Closes #498
@olemb I don't have enough permissions on PyPI to create the necessary token for the last step. Once this is merged and tested, please create one and put it in a GitHub secret named `PROD_PYPI_TOKEN` to enable the effectively releasing to pypi.org. Everything you need to know is in the `release.yml` file comments if need be.
> Release automation prototype

- mido/midifiles/meta.py
For some MIDI files the parameter `type` is passed to the constructor resulting in an TypeError. This workaround should fix this without changing anything else.
> Make `UnknownMetaMessage` robust to faulty MIDIs

- mido/backends/portmidi.py
Fix for error:
AttributeError: module 'mido.backends.portmidi_init' has no attribute 'c_char_p'
> fix portmidi backend sysex

- mido/midifiles/midifiles.py
Follows up on #470.
There's no point in computing `merged_track` (quite expensively) until it's needed.
However, the comment https://github.com/mido/mido/pull/470#issuecomment-1705069143 should be addressed (separately): it's not clear that `merged_track` is a cached object, and changes to `tracks` or their contents will not be reflected automatically.
> Defer computing merged_track

- mido/messages/messages.py
- mido/midifiles/midifiles.py
- mido/midifiles/tracks.py
- tests/midifiles/test_tracks.py
Closes #472 
Small and low priority performance enhancement to `mido.merge_tracks`. Skip redundant data checks. When you have a `MidiFile` that you want to iterate over, its messages should already have passed `mido.checks`. 
I made `merge_tracks` skip the checks by default, but since it is exposed to clients, maybe it should continue existing behavior by default and only change for internal invocations (like iterating over a `MidiFile`).
> Faster merge tracks

- examples/backends/rtm.py
- mido/backends/amidi.py
- mido/backends/portmidi.py
- mido/backends/rtmidi.py
- mido/backends/rtmidi_python.py
- mido/messages/decode.py
- mido/messages/strings.py
- mido/midifiles/meta.py
- mido/midifiles/midifiles.py
- mido/sockets.py
- pyproject.toml
- tests/messages/test_messages.py
- tests/midifiles/test_meta.py
- tests/midifiles/test_midifiles.py
- tests/midifiles/test_tracks.py
- tests/test_frozen.py
- tests/test_parser.py
Each commit enables a given category and addresses it to some degree.
As for S307 in tests, I'm not sure it makes much sense for `repr`s for messages to be `eval`able (since eval is evil); perhaps that should be changed for 2.0...
> Enable a bunch more Ruff categories

- mido/midifiles/meta.py
- tests/midifiles/test_tracks.py
Quick fix to address #570 
I missed this message in the initial implementation of `skip_checks`. Sorry. Let's make sure we cover all our cases this time.
```
➜  mido git:(main) ✗ grep -R "class.*Message" mido
Binary file mido/messages/__pycache__/messages.cpython-310.pyc matches
mido/messages/messages.py:class BaseMessage:
mido/messages/messages.py:class Message(BaseMessage):
mido/frozen.py:class FrozenMessage(Frozen, Message):
mido/frozen.py:class FrozenMetaMessage(Frozen, MetaMessage):
mido/frozen.py:class FrozenUnknownMetaMessage(Frozen, UnknownMetaMessage):
mido/frozen.py:        class_ = FrozenMessage
mido/frozen.py:        class_ = FrozenUnknownMetaMessage
mido/frozen.py:        class_ = FrozenMetaMessage
mido/frozen.py:        class_ = Message
mido/frozen.py:        class_ = …
```
> Update meta messages for skip_checks arg
